### PR TITLE
Allow customization of FontAtlas in subclassed FontSystem

### PR DESCRIPTION
**Pull request by claytonsingh**
Minimal example enabling using one font atlas for multiple fonts.
```
class SharedFontSystem : FontSystem
{
	public static FontAtlas m_sharedFontAtlas = null;
	public static readonly List<SharedFontSystem> SharedFontSystems = new List<SharedFontSystem>();
	public static int Size = 1024;

	public SharedFontSystem()
	{
		SharedFontSystems.Add(this);
	}

	protected override FontAtlas CreateNewAtlas(int textureWidth, int textureHeight)
	{
		if (ExistingTexture == null && Atlases.Count == 0)
		{
			m_sharedFontAtlas ??= base.CreateNewAtlas(Size, Size);
			return m_sharedFontAtlas;
		}
		return base.CreateNewAtlas(textureWidth, textureHeight);
	}

	public static void ResetAll()
	{
		m_sharedFontAtlas = null;
		foreach (SharedFontSystem sfs in SharedFontSystems)
		{
			sfs.Reset();
		}
	}
}
```

### CODE REVIEW

**Comment by rds1983** [comment]
Probably it's better to add delegate `Func<int, int, FontAtlas> CreateNewAtlas` to the FontSystemSettings.

**Comment by claytonsingh** [comment]
I have added `CreateNewAtlas` as a setting.

It may be a better solution to factor atlas management out of FontSystem into a `FontAtlasCollection` and include that into the settings. This would entale moving/proxying `RenderGlyphOnAtlas`, `GetCurrentAtlas`, and `_currentAtlas` into another class.

I am going to try out this method in a branch to see how it looks by comparison in another branch. So I have marked this as a draft for now.

**Comment by claytonsingh** [comment]
@rds1983 I have a competing solution in https://github.com/FontStashSharp/FontStashSharp/pull/77.

Let me know what method you like better.

**Comment by rds1983** [comment]
I like this one.

**Comment by claytonsingh** [comment]
I just discovered a subtle bug with this implementation when sharing more then just the first atlas.
1. With `FontSystem A` write 1 or more glyfs
2. With `FontSystem B` fill the first two atlases but dont trigger `CurrentAtlasFull` on the second atlas
3. With `FontSystem A` write 1 glyf

This will trigger _Could not add rect to the newly created atlas_ exception. As the current atlas on A is full and the new atlas provided is also full.

Any thoughts on how to resolve this?

**Comment by claytonsingh** [comment]
Closing in favor of https://github.com/FontStashSharp/FontStashSharp/pull/78

**Pull request closed without merging**
